
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2012-2019 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("1.1.7")]
[assembly: AssemblyFileVersion("1.1.7")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("YAZA/YAZD")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2019, 12, 20, 4, 50, 26, DateTimeKind.Utc);
}
	